name: "hello world"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        shell: bash
        run: echo "hello world"
